# Generated by Django 2.1.1 on 2018-10-11 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20181004_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Building')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Country')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Companies')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Office')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Building')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Companies')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Region')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Companies')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Street')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.City')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Companies')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Companies'),
        ),
        migrations.AddField(
            model_name='city',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Companies'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Region'),
        ),
        migrations.AddField(
            model_name='building',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Companies'),
        ),
        migrations.AddField(
            model_name='building',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Street'),
        ),
    ]
