# Generated by Django 2.1.1 on 2018-10-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20181011_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='company',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
