# Generated by Django 2.1.1 on 2018-10-14 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20181014_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Companies'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Country'),
        ),
    ]
