# Generated by Django 2.1.1 on 2018-10-14 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20181015_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Companies'),
        ),
    ]
