# Generated by Django 2.1.1 on 2018-10-15 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20181015_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
